-- AbcMattress

DELETE FROM AbcMattress;
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Cassatt-Ultra','Stearns & Foster Lux Estate','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('CopperII-Plush','Sealy Hybrid','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Q8-Number-Bed','Sealy Hybrid','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('MACKINACK-CF','Spring Air','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('GRAND-HAVEN-CF','Spring Air','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('SILVIRAZ-CF','Spring Air','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('SILVIRAZ-PL','Spring Air','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('CHESTNUT-STREET','Sealy Hybrid','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('CONFORM','Sealy Hybrid','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Q8-Flexhead-Num','Instant Comfort','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Rockwell-Firm','Stearns & Foster Estate','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Hurston','Stearns & Foster Estate','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Rockwell-Plush','Stearns & Foster Estate','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Q8-Number-Bed','Instant Comfort','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Cassatt-Plush','Stearns & Foster Lux Estate','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('NECTAR','Nectar','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Baldwin','Aireloom','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('ROSE','Aireloom','Ultra Luxury Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Luxe-Adapt-Firm','Tempurpedic Luxe-Adapt','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Luxe-Adapt-PL','Tempurpedic Luxe-Adapt','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Alverson','Serta','Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Pro-Adapt-Soft','Tempurpedic Pro-Adapt','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Pro-Adapt-Med','Tempurpedic Pro-Adapt','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Pro-Adapt-Firm','Tempurpedic Pro-Adapt','Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Adapt-Medium','Tempurpedic Adapt','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Adapt-Hybrid-Me','Tempurpedic Adapt','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Pro-Adapt-HYB-M','Tempurpedic Pro-Adapt','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('BRX1000C-Hyb-PL','Beautyrest','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('BR800-CF','Beautyrest','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Dewitt','Serta','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('TrustII-Hybrid','Sealy Hybrid','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('KelburnII','Sealy Hybrid','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Luxe-Breeze-PL','Tempurpedic Breeze','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Luxe-Breeze-CF','Tempurpedic Breeze','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Pro-Breeze-Med','Tempurpedic Breeze','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Pro-Breeze-HYB','Tempurpedic Breeze','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('CONTENTO-FIRM','Sealy Posturpedic','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('CopperII-Plush','Sealy Hybrid','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('CopperII-Firm','Sealy Hybrid','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Harmony-Lux-XFM','Beautyrest','Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Uncommon-Firm','Sealy Posturpedic','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('BILLINGS','Sealy Posturpedic','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Mirabai','Sealy Posturpedic','Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('CONTENTO-PLUSH','Sealy Posturpedic','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Tofte','Aireloom','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Harbor','Aireloom','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Baldwin','Aireloom','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('SLEEP-RITE-II','Spring Air','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('DESTINYII','Spring Air','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('X-Class-Hyb-PL','Beautyrest Black Series Hybrid','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('X-Class-Hyb-CF','Beautyrest Black Series Hybrid','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('MACKINACK-PL','Spring Air','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('BR800-Plush','Beautyrest','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Carrollton','Serta','Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('BRX1000IP-Hyb-M','Beautyrest','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('BR800-Medium','Beautyrest','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('SIGNATUREII-PL','Spring Air','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('SIGNATUREII-CF','Spring Air','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('ROSE','Restonic','Ultra Luxury Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('ST.CLAIR','Restonic','Cushion-Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('MARIGOLD','Restonic','Firm');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('Malloy','Serta','Plush');
INSERT INTO AbcMattress(Model,Brand,Comfort) VALUES ('CHESTNUT-STREET','Sealy','Plush');

-- AbcMattressBase
DELETE FROM AbcMattressBase;
